# This is a basic workflow to help you get started with Actions

name: build-master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ test-build ]
  pull_request:
    branches: [ test-build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@test-build

      #Run Nuget Restore
      - name: Install NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Restore NuGet packages
        working-directory: WebApp
        run: nuget restore PharmaBox.sln

      #Run Build DotNet Core
      - name: Build DotNet Core
        working-directory: WebApp
        run: msbuild PharmaBox.sln

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
